### ISSUE TITLE
font origin issue

### ISSUE THREAD

**Issue by RosaWagner** [bghryct/SplineSansMono#3]
@bghryct  Please declare the same font origin for Roman and Italic.
add font info parameter `Variable Font Origin` and set it to `Regular` in each sources, and re-build fonts.

**Comment by bghryct** [comment]
@RosaWagner This should be solved now. 

Updated VF origin in italic to be the regular in the italic, and kept the VF origin the same in the roman as it was already regular. Then updated the fonts folder with the updated fonts build.

**Comment by bghryct** [comment]
As I think this is solved I'm closing the issue.
